# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 946780190c99c9e93d543dcedf864eb1031c74085d62b4e108d2ed34f8af482658b52eed493400bac5d42dfcf24a038cf18a8247b3e4713412d9f0d6b5da803d

test:
  secret_key_base: af12d397fce0cf7a830153d4d66ce0f3acae42a376589eddfab2486f59d2c8e7f16e4e02521e328f8ee51966a78ad0c0dc3827d166341ce8084ee63842cb0b53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
